### PR TITLE
Create a library to integrate `oxidized_navigation` with `bevy_landmass`.

### LINKED ISSUE #46: Create an integration for `oxidized_navigation`.
I would like to have a crate to add `oxidized_navigation` support to `landmass` so that `oxidized_navigation` can be responsible for generating the nav meshes, while `landmass` will be responsible for path finding and steering.

### PR DESCRIPTION
**Pull request by andriyDev**
Fixes #46.

### CODE REVIEW

**Comment by andriyDev** [comment]
I need to wait for oxidized_navigation to upgrade to Bevy 0.14.

Some other TODOs: add tests for `landmass_oxidized_navigation`.

**Comment by masonk** [comment]
I was just looking for this. These things seem to go together, it's great to have an integration for them.

**Comment by masonk** [comment]
FWIW, oxidized_navigation is on .14 now.

**Comment by andriyDev** [comment]
I'm happy with the state of this as a V0.

**Pull request merged**
